package br.com.saqz.groups.adapter.input.http

import br.com.saqz.groups.application.finance.charge.*
import br.com.saqz.groups.domain.finance.charge.*
import br.com.saqz.sharedkernel.RequestIdentity
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import org.springframework.http.ResponseEntity
import org.springframework.security.core.annotation.AuthenticationPrincipal
import org.springframework.web.bind.annotation.*
import java.time.*
import java.util.UUID

data class MonthlyChargeRequest @JsonCreator constructor(@JsonProperty("requestId") val requestId:UUID?,@JsonProperty("month") val month:String?,@JsonProperty("amountCents") val amountCents:Long?,@JsonProperty("dueDate") val dueDate:LocalDate?,@JsonProperty("memberIds") val memberIds:Set<UUID>?)
data class ChargeStatusRequest @JsonCreator constructor(@JsonProperty("status") val status:String?,@JsonProperty("note") val note:String?=null)
data class ChargeEventResponse(val actorId:UUID,val oldStatus:String,val newStatus:String,val note:String?,val occurredAt:Instant)
data class ChargeResponse(val id:UUID,val groupId:UUID,val memberId:UUID,val kind:String,val gameId:UUID?,val month:String?,val amountCents:Long,val dueDate:LocalDate,val status:String,val reviewRequired:Boolean=false,val version:Long,val events:List<ChargeEventResponse>)
data class ChargeListResponse(val charges:List<ChargeResponse>,val pendingTotalCents:Long?=null,val paidTotalCents:Long?=null,val waivedTotalCents:Long?=null,val cancelledTotalCents:Long?=null)

@RestController class ChargeController(private val actors:VerifiedGroupActorResolver,private val management:ChargeManagement,private val generation:ChargeTransactions){
    @GetMapping("/api/groups/{groupId}/charges") fun organizer(@AuthenticationPrincipal identity:RequestIdentity,@PathVariable groupId:String)=list(management.listOrganizer(actors.resolve(identity),uuid(groupId)))
    @GetMapping("/api/groups/{groupId}/charges/me") fun own(@AuthenticationPrincipal identity:RequestIdentity,@PathVariable groupId:String)=list(management.listOwn(actors.resolve(identity),uuid(groupId)))
    @PostMapping("/api/groups/{groupId}/charges/monthly") fun monthly(@AuthenticationPrincipal identity:RequestIdentity,@PathVariable groupId:String,@RequestBody request:MonthlyChargeRequest):ChargeListResponse{val actor=actors.resolve(identity);when(management.listOrganizer(actor,uuid(groupId))){ChargeListResult.Hidden->throw GameNotFoundException();ChargeListResult.Forbidden->throw AccessForbiddenException();is ChargeListResult.Success->Unit};val command=MonthlyGenerationCommand(request.requestId?:invalid("requestId"),uuid(groupId),actor,request.month?.let{runCatching{YearMonth.parse(it)}.getOrNull()}?:invalid("month"),request.amountCents?:invalid("amountCents"),request.dueDate?:invalid("dueDate"),request.memberIds?:invalid("memberIds"));return when(val result=generation.generate(command)){is MonthlyGenerationResult.Success->ChargeListResponse(result.charges.map{ChargeWithEvents(it,emptyList()).response()});is MonthlyGenerationResult.Invalid->throw InvalidGroupRequestException(result.fields.associateWith{listOf("is invalid")});MonthlyGenerationResult.Hidden->throw GameNotFoundException()}}
    @PostMapping("/api/groups/{groupId}/charges/{chargeId}/status") fun status(@AuthenticationPrincipal identity:RequestIdentity,@PathVariable groupId:String,@PathVariable chargeId:String,@RequestHeader("If-Match",required=false) ifMatch:String?,@RequestBody request:ChargeStatusRequest):ResponseEntity<ChargeResponse>{val target=request.status?.let{runCatching{ChargeStatus.valueOf(it)}.getOrNull()}?:invalid("status");return when(val result=management.status(actors.resolve(identity),uuid(groupId),uuid(chargeId),version(ifMatch),ChargeStatusCommand(target,request.note))){is ChargeStatusResult.Success->ResponseEntity.ok().eTag(result.value.charge.version.toString()).body(result.value.response());ChargeStatusResult.Hidden->throw GameNotFoundException();ChargeStatusResult.Forbidden->throw AccessForbiddenException();ChargeStatusResult.Conflict->throw VersionConflictException();ChargeStatusResult.InvalidTransition->throw InvalidGameTransitionException();ChargeStatusResult.InvalidNote->throw InvalidGroupRequestException(mapOf("note" to listOf("is invalid")))}}
    private fun list(result:ChargeListResult)=when(result){is ChargeListResult.Success->ChargeListResponse(result.charges.map{it.response()},result.totals?.pendingCents,result.totals?.paidCents,result.totals?.waivedCents,result.totals?.cancelledCents);ChargeListResult.Hidden->throw GameNotFoundException();ChargeListResult.Forbidden->throw AccessForbiddenException()}
    private fun uuid(value:String)=runCatching{UUID.fromString(value)}.getOrElse{throw GameNotFoundException()};private fun version(value:String?):Long{if(value==null)throw PreconditionRequiredException();return Regex("\"([1-9][0-9]*)\"").matchEntire(value)?.groupValues?.get(1)?.toLong()?:invalid("ifMatch")};private fun invalid(field:String):Nothing=throw InvalidGroupRequestException(mapOf(field to listOf("is required or invalid")))
}
private fun ChargeWithEvents.response():ChargeResponse{val identity=charge.identity;return ChargeResponse(charge.id,charge.groupId,charge.memberId,if(identity is ChargeIdentity.Game)"GAME" else "MONTHLY",(identity as? ChargeIdentity.Game)?.gameId,(identity as? ChargeIdentity.Monthly)?.month?.toString(),charge.amountCents,charge.dueDate,charge.status.name,charge.reviewRequired,charge.version,events.map{ChargeEventResponse(it.actorId,it.oldStatus.name,it.newStatus.name,it.note,it.occurredAt)})}
