const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const source=require('node:fs').readFileSync(require.resolve('../index.html'),'utf8').match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
const flush=()=>new Promise(setImmediate);
const globalData={version:7,systems:[{system:'BACKEND',mode:'OFF'},{system:'MOBILE',mode:'OFF'}]};
const userData={userId:'test-user',version:4,overrides:[{system:'BACKEND',decision:'INHERIT'},{system:'MOBILE',decision:'INHERIT'}],accountId:null,backendEnabled:false,mobileEnabled:false,accountOperationsEnabled:null};
function setup(){
 let session; const requests=[],timers=new Map();
 const context=vm.createContext({DCLogic:class{props={};setState(p,cb){Object.assign(this.state,p);cb?.();}},window:{crypto:require('node:crypto'),saqzAdmin:{me:{},onSession(fn){session=fn;},fetchAdmin(path,options){return new Promise((resolve,reject)=>requests.push({path,options,resolve,reject}));}}},setTimeout(fn){let id=Symbol();timers.set(id,fn);return id;},clearTimeout(id){timers.delete(id);}});
 const App=vm.runInContext(source+'\nComponent',context);const app=new App();app.componentDidMount();app.recApply('global',globalData);
 return {app,requests,timers,logout(){session(null);}};
}
const ok=data=>({ok:true,status:200,json:async()=>data});
const draft={method:'PIX',termsVersion:'v1',effectiveAt:'2099-01-01T12:00',commissionRate:'1,23456789',commissionFixedCents:'0',baseCents:'100,01'};
const prepare=()=>{const h=setup();h.app.state.conditions.fees.draft={...draft};h.app.state.conditions.terms.draft={version:'v1',content:'Termos de teste',effectiveAt:draft.effectiveAt};return h;};
const success=(request,value={kind:'TERMS',resourceId:'v1',effectiveAt:'2099-01-01T15:00:00Z',publishedAt:'2026-09-13T00:00:00Z'})=>ok({value,requestId:JSON.parse(request.options.body).requestId});
test('decimal conversions are exact strings, including cents beyond JS safe integers',()=>{const {app}=prepare();let b=app.conditionBody('fees',true);assert.equal(b.commissionRate,'0.0123456789');assert.equal(b.providerRate,undefined);assert.equal(b.providerFixedCents,undefined);assert.equal(b.baseCents,'10001');app.conditionEdit('fees','baseCents','92233720368547758,07');assert.equal(app.conditionBody('fees',true).baseCents,'9223372036854775807');});
test('invalid money, rates, empty fields and missing method never send',async()=>{for(const [field,value] of [['commissionRate','0.000000001'],['commissionRate','100.01'],['commissionFixedCents','1.001'],['commissionFixedCents','-1'],['commissionFixedCents','1e2'],['commissionFixedCents',''],['baseCents','0'],['baseCents','92233720368547758.08'],['method','']]){const {app,requests}=prepare();app.conditionEdit('fees',field,value);await app.conditionSend('fees',true);assert.equal(requests.length,0,field+value);}});
test('terms validation blocks blank/oversize content, bad version and past effective date',async()=>{for(const [field,value] of [['content',' '],['content','x'.repeat(200001)],['version','invalid space'],['effectiveAt','2000-01-01T00:00']]){const {app,requests}=prepare();app.conditionEdit('terms',field,value);await app.conditionSend('terms');assert.equal(requests.length,0);}});
test('both methods publish only explicitly and publication excludes simulation base',async()=>{for(const method of ['PIX','CARD']){const {app,requests}=prepare();app.conditionEdit('fees','method',method);assert.equal(requests.length,0);const p=app.conditionSend('fees');const b=JSON.parse(requests[0].options.body);assert.equal(b.method,method);assert.equal(b.baseCents,undefined);assert.equal(requests[0].path,'/admin/receivables/fees');requests[0].resolve(success(requests[0]));await p;assert.match(app.state.conditions.fees.status,/confirmada/);}});
test('timeout locks drafts and preserves byte-identical publication without revalidating the draft',async()=>{const {app,requests,timers}=prepare();const p=app.conditionSend('terms');for(const t of timers.values())t();await p;app.conditionEdit('terms','content','changed');assert.equal(app.state.conditions.terms.draft.content,'Termos de teste');const retry=app.conditionSend('terms');assert.equal(requests[1].options.body,requests[0].options.body);requests[1].resolve(success(requests[1]));await retry;requests[0].resolve(success(requests[0],{resourceId:'STALE'}));await flush();assert.doesNotMatch(app.state.conditions.terms.resultText,/STALE/);});
test('409 is visible, permits correction and new explicit publication gets new identity',async()=>{const {app,requests}=prepare();let p=app.conditionSend('terms');requests[0].resolve({ok:false,status:409,json:async()=>({error:'CONFLICT'})});await p;assert.match(app.state.conditions.terms.status,/Conflito/);app.conditionEdit('terms','version','v2');p=app.conditionSend('terms');assert.notEqual(JSON.parse(requests[0].options.body).requestId,JSON.parse(requests[1].options.body).requestId);requests[1].resolve(success(requests[1]));await p;});
test('simulation displays all six backend values and clears when draft changes',async()=>{const {app,requests}=prepare();const p=app.conditionSend('fees',true);assert.equal(requests[0].path,'/admin/receivables/fees/simulate');requests[0].resolve(success(requests[0],{baseCents:10001,feesCents:701,totalCents:10702,expectedNetCents:10001,commissionCents:200,providerFeeCents:501}));await p;assert.match(app.state.conditionQuote,/Total a pagar: R\$ 107,02/);assert.equal(app.state.conditionQuote.split('\n').length,6);app.conditionEdit('fees','method','CARD');assert.equal(app.state.conditionQuote,'');});
test('malformed envelope or server failure keeps publication retry identity',async()=>{for(const response of [ok({value:{},requestId:'wrong'}),{ok:false,status:503,json:async()=>({error:'unavailable'})}]){const {app,requests}=prepare();const p=app.conditionSend('terms');requests[0].resolve(response);await p;assert.equal(app.state.conditions.terms.pending,true);assert.match(app.state.conditions.terms.status,/incerto/);}});
test('logout purges private conditions and invalidates late responses',async()=>{const {app,requests,logout}=prepare();const p=app.conditionSend('terms');logout();requests[0].resolve(success(requests[0]));await flush();assert.equal(app.state.conditions.terms.draft.content,'');assert.equal(app.state.conditions.terms.resultText,'');assert.equal(Object.keys(app._conditionsPending).length,0);assert.equal(app.state.conditionQuote,'');});
test('unsafe backend monetary numbers are refused rather than rounded',async()=>{const {app,requests}=prepare();const p=app.conditionSend('fees',true);requests[0].resolve(success(requests[0],{baseCents:9007199254740992}));await p;assert.equal(app.state.conditionQuote,'');assert.match(app.state.conditions.fees.status,/exata/);});

test('provider tariffs cannot enter a publication or simulation payload through stale drafts',()=>{
 const {app}=prepare();app.state.conditions.fees.draft.providerRate='99';app.state.conditions.fees.draft.providerFixedCents='999';
 for(const simulate of [false,true]){const b=app.conditionBody('fees',simulate);assert.equal(b.providerRate,undefined);assert.equal(b.providerFixedCents,undefined);}
});
