package br.com.saqz.sharedkernel

enum class ErrorCode {
    AUTHENTICATION_REQUIRED,
    EMAIL_NOT_VERIFIED,
    IDENTITY_PROVIDER_UNAVAILABLE,
    VALIDATION_FAILED,
    GROUP_NOT_FOUND,
    ACCESS_FORBIDDEN,
}
