package br.com.saqz.sharedkernel

enum class ErrorCode {
    AUTHENTICATION_REQUIRED,
    EMAIL_NOT_VERIFIED,
    IDENTITY_PROVIDER_UNAVAILABLE,
    VALIDATION_FAILED,
    GROUP_NOT_FOUND,
    ACCESS_FORBIDDEN,
    PRECONDITION_REQUIRED,
    VERSION_CONFLICT,
    INVITE_INVALID_OR_EXPIRED,
    INVITE_ATTEMPT_LIMIT,
    PHOTO_INVALID,
    PHOTO_TOO_LARGE,
    GAME_NOT_FOUND,
    INVALID_GAME_TRANSITION,
    ATTENDANCE_DEADLINE_PASSED,
    ATTENDANCE_FROZEN,
}
