package br.com.saqz.groups.adapter.input.http

import br.com.saqz.groups.application.create.TransactionRunner
import br.com.saqz.groups.application.finance.charge.*
import br.com.saqz.groups.domain.GroupRole
import br.com.saqz.groups.domain.finance.charge.*
import br.com.saqz.sharedkernel.RequestIdentity
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.time.*
import java.util.UUID
import kotlin.test.*

class ChargeControllerTest{
    private val actor=UUID.randomUUID();private val group=UUID.randomUUID();private val member=actor;private lateinit var repo:MemoryRepo;private lateinit var controller:ChargeController
    @BeforeEach fun setup(){repo=MemoryRepo();val tx=object:TransactionRunner{override fun<T> inTransaction(block:()->T)=block()};controller=ChargeController(VerifiedGroupActorResolver{actor},ChargeManagement(tx,repo,{NOW},{UUID.randomUUID()}),ChargeTransactions(tx,repo){NOW})}
    @Test fun `organizer list returns charges totals and exact manual fields`(){repo.role=GroupRole.OWNER;repo.seed(member,2500);val response=controller.organizer(ID,"$group");assertEquals(1,response.charges.size);assertEquals(2500,response.pendingTotalCents);assertEquals(2500,response.charges.single().amountCents);assertEquals("GAME",response.charges.single().kind)}
    @Test fun `admin has organizer visibility`(){repo.role=GroupRole.ADMIN;repo.seed(UUID.randomUUID(),2500);assertEquals(1,controller.organizer(ID,"$group").charges.size)}
    @Test fun `athlete cannot list group charges or totals`(){repo.role=GroupRole.ATHLETE;assertFailsWith<AccessForbiddenException>{controller.organizer(ID,"$group")}}
    @Test fun `nonmember organizer list is hidden`(){repo.role=null;assertFailsWith<GameNotFoundException>{controller.organizer(ID,"$group")}}
    @Test fun `athlete own route returns only own charges without totals`(){repo.role=GroupRole.ATHLETE;repo.seed(actor,100);repo.seed(UUID.randomUUID(),200);val response=controller.own(ID,"$group");assertEquals(listOf(actor),response.charges.map{it.memberId});assertNull(response.pendingTotalCents)}
    @Test fun `malformed group id is privacy hidden`(){assertFailsWith<GameNotFoundException>{controller.own(ID,"bad")}}
    @Test fun `monthly generation selects active members and reviewed values`(){repo.role=GroupRole.OWNER;repo.active=setOf(actor);val response=controller.monthly(ID,"$group",monthly());assertEquals(1,response.charges.size);assertEquals(3000,response.charges.single().amountCents);assertEquals("2026-08",response.charges.single().month)}
    @Test fun `monthly retry returns equivalent immutable charge`(){repo.role=GroupRole.OWNER;repo.active=setOf(actor);val first=controller.monthly(ID,"$group",monthly()).charges.single();val retry=controller.monthly(ID,"$group",monthly().copy(amountCents=9000)).charges.single();assertEquals(first.id,retry.id);assertEquals(3000,retry.amountCents)}
    @Test fun `monthly validates required and bounded values`(){repo.role=GroupRole.OWNER;assertFailsWith<InvalidGroupRequestException>{controller.monthly(ID,"$group",monthly().copy(requestId=null))};assertFailsWith<InvalidGroupRequestException>{controller.monthly(ID,"$group",monthly().copy(amountCents=0))}}
    @Test fun `monthly rejects selection of a non member`(){repo.role=GroupRole.OWNER;repo.active=emptySet();assertFailsWith<InvalidGroupRequestException>{controller.monthly(ID,"$group",monthly())}}
    @Test fun `monthly excludes inactive members and reports how many`(){repo.role=GroupRole.OWNER;repo.active=setOf(actor);repo.inactive=setOf(actor);val response=controller.monthly(ID,"$group",monthly());assertEquals(0,response.charges.size);assertEquals(1,response.excludedInactiveMemberCount)}
    @Test fun `athlete cannot generate monthly charges`(){repo.role=GroupRole.ATHLETE;assertFailsWith<AccessForbiddenException>{controller.monthly(ID,"$group",monthly())}}
    @Test fun `status update requires quoted If Match`(){repo.role=GroupRole.OWNER;val c=repo.seed(actor,100);assertFailsWith<PreconditionRequiredException>{controller.status(ID,"$group","${c.id}",null,ChargeStatusRequest("PAID"))};assertFailsWith<InvalidGroupRequestException>{controller.status(ID,"$group","${c.id}","1",ChargeStatusRequest("PAID"))}}
    @Test fun `status update derives actor time old state audit and etag`(){repo.role=GroupRole.OWNER;val c=repo.seed(actor,100);val response=controller.status(ID,"$group","${c.id}","\"1\"",ChargeStatusRequest("PAID","Recebido"));assertEquals("\"2\"",response.headers.eTag);assertEquals("PAID",response.body!!.status);val event=response.body!!.events.last();assertEquals(actor,event.actorId);assertEquals("PENDING",event.oldStatus);assertEquals(NOW,event.occurredAt)}
    @Test fun `status command cannot fabricate amount member or actor`(){assertEquals(setOf("status","note"),ChargeStatusRequest::class.java.declaredFields.filterNot{it.isSynthetic}.map{it.name}.toSet())}
    @Test fun `stale status is conflict and preserves charge`(){repo.role=GroupRole.OWNER;val c=repo.seed(actor,100);assertFailsWith<VersionConflictException>{controller.status(ID,"$group","${c.id}","\"2\"",ChargeStatusRequest("PAID"))};assertEquals(ChargeStatus.PENDING,repo.rows.getValue(c.id).charge.status)}
    @Test fun `invalid or repeated transition is stable lifecycle error`(){repo.role=GroupRole.OWNER;val c=repo.seed(actor,100,status=ChargeStatus.PAID);assertFailsWith<InvalidGameTransitionException>{controller.status(ID,"$group","${c.id}","\"1\"",ChargeStatusRequest("WAIVED"))};assertFailsWith<InvalidGroupRequestException>{controller.status(ID,"$group","${c.id}","\"1\"",ChargeStatusRequest("SETTLED"))}}
    @Test fun `athlete status is forbidden and nonmember is hidden`(){val c=repo.seed(actor,100);repo.role=GroupRole.ATHLETE;assertFailsWith<AccessForbiddenException>{controller.status(ID,"$group","${c.id}","\"1\"",ChargeStatusRequest("PAID"))};repo.role=null;assertFailsWith<GameNotFoundException>{controller.status(ID,"$group","${c.id}","\"1\"",ChargeStatusRequest("PAID"))}}
    @Test fun `unknown charge and malformed id are hidden`(){repo.role=GroupRole.OWNER;assertFailsWith<GameNotFoundException>{controller.status(ID,"$group","${UUID.randomUUID()}","\"1\"",ChargeStatusRequest("PAID"))};assertFailsWith<GameNotFoundException>{controller.status(ID,"$group","bad","\"1\"",ChargeStatusRequest("PAID"))}}
    @Test fun `responses contain no processed or settlement claims`(){val names=(ChargeResponse::class.java.declaredFields+ChargeListResponse::class.java.declaredFields).map{it.name.lowercase()};assertFalse(names.any{it.contains("processed")||it.contains("settled")||it.contains("processor")})}

    private fun monthly()=MonthlyChargeRequest(UUID.randomUUID(),"2026-08",3000,LocalDate.of(2026,8,10),setOf(actor))
    private inner class MemoryRepo:ChargeManagementRepository,ChargeTransactionRepository{var role:GroupRole?=GroupRole.OWNER;var active:Set<UUID>?=setOf(actor);var inactive:Set<UUID> = emptySet();val rows=linkedMapOf<UUID,ChargeWithEvents>();override fun role(actorId:UUID,groupId:UUID)=if(groupId==group)role else null;override fun list(groupId:UUID,memberId:UUID?)=rows.values.filter{memberId==null||it.charge.memberId==memberId};override fun find(groupId:UUID,chargeId:UUID)=rows[chargeId];override fun update(change:ChargeChange,expectedVersion:Long):Boolean{val old=rows[change.charge.id]?:return false;if(old.charge.version!=expectedVersion)return false;rows[change.charge.id]=ChargeWithEvents(change.charge,old.events+change.event);return true};override fun createGameCharge(input:GameChargeInput,actorId:UUID,now:Instant)=rows.values.firstOrNull{(it.charge.identity as? ChargeIdentity.Game)?.gameId==input.gameId&&it.charge.memberId==input.memberId}?.charge?:seed(input.memberId,requireNotNull(input.gameFeeCents),ChargeIdentity.Game(input.gameId));override fun reconcileGameCancellation(groupId:UUID,gameId:UUID,actorId:UUID,now:Instant)=Unit;override fun members(groupId:UUID)=if(groupId==group)active?.let{GroupMembers(it,it-inactive)} else null;override fun createMonthlyCharge(command:MonthlyGenerationCommand,memberId:UUID,now:Instant)=rows.values.firstOrNull{(it.charge.identity as? ChargeIdentity.Monthly)?.month==command.month&&it.charge.memberId==memberId}?.charge?:seed(memberId,command.amountCents,ChargeIdentity.Monthly(command.month),due=command.dueDate);fun seed(member:UUID,amount:Long,identity:ChargeIdentity=ChargeIdentity.Game(UUID.randomUUID()),status:ChargeStatus=ChargeStatus.PENDING,due:LocalDate=LocalDate.of(2026,8,10)):Charge{val c=Charge(UUID.randomUUID(),group,member,identity,amount,due,status);rows[c.id]=ChargeWithEvents(c,emptyList());return c}}
    private companion object{val ID=RequestIdentity("subject",emailVerified=true,displayName="Player");val NOW=Instant.parse("2026-08-01T10:00:00Z")}
}
