package br.com.saqz.groups.adapter.input.http

import br.com.saqz.groups.application.game.recurrence.GameIdFactory
import br.com.saqz.groups.application.game.series.*
import br.com.saqz.groups.domain.GroupRole
import br.com.saqz.groups.domain.game.GameVenueSnapshot
import br.com.saqz.groups.domain.game.recurrence.WeeklySeriesRule
import br.com.saqz.groups.domain.game.recurrence.WeeklySlotRule
import br.com.saqz.sharedkernel.RequestIdentity
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.time.*
import java.util.UUID
import kotlin.test.*

class WeeklySeriesControllerTest {
    private val actor=UUID.randomUUID();private val group=UUID.randomUUID();private lateinit var repository:MemorySeriesRepository;private lateinit var boundaryRepository:MemoryBoundaryRepository;private lateinit var service:WeeklySeriesService;private lateinit var controller:WeeklySeriesController
    @BeforeEach fun setup(){repository=MemorySeriesRepository();boundaryRepository=MemoryBoundaryRepository();service=WeeklySeriesService(repository,GameIdFactory(UUID::randomUUID),CLOCK);controller=WeeklySeriesController(VerifiedGroupActorResolver{actor},service,ApplySeriesBoundary(boundaryRepository,UUID::randomUUID,CLOCK))}

    @Test fun `owner creates bounded twelve week series`() { val result=assertIs<WeeklySeriesResult.Success>(service.create(actor,rule()));assertEquals(12,result.series.occurrences.size);assertTrue(result.series.occurrences.all{it.localDate<DATE.plusWeeks(12)}) }
    @Test fun `admin creates series`() {repository.actorRole=GroupRole.ADMIN;assertIs<WeeklySeriesResult.Success>(service.create(actor,rule()))}
    @Test fun `athlete cannot create series`() {repository.actorRole=GroupRole.ATHLETE;assertEquals(WeeklySeriesResult.Forbidden,service.create(actor,rule()))}
    @Test fun `nonmember create is hidden`() {repository.actorRole=null;assertEquals(WeeklySeriesResult.NotFound,service.create(actor,rule()))}
    @Test fun `invalid recurrence returns all errors before write`() {val invalid=rule().copy(zoneId="bad zone",slots=emptyList());val result=assertIs<WeeklySeriesResult.Invalid>(service.create(actor,invalid));assertEquals(setOf("zoneId","slots"),result.errors.map{it.field}.toSet());assertEquals(0,repository.createCalls)}
    @Test fun `create retry is equivalent and does not duplicate occurrences`() {val rule=rule();assertFalse(assertIs<WeeklySeriesResult.Success>(service.create(actor,rule)).replay);assertTrue(assertIs<WeeklySeriesResult.Success>(service.create(actor,rule)).replay);assertEquals(12,repository.views.getValue(rule.seriesId).occurrences.size)}
    @Test fun `member reads current local rule`() {val rule=rule();service.create(actor,rule);val result=assertIs<WeeklySeriesResult.Success>(service.read(actor,group,rule.seriesId));assertEquals(rule.zoneId,result.series.rule.zoneId);assertEquals(rule.slots.single().localTime,result.series.rule.slots.single().localTime)}
    @Test fun `unknown series is privacy not found`() {assertEquals(WeeklySeriesResult.NotFound,service.read(actor,group,UUID.randomUUID()))}
    @Test fun `multi slot creation preserves stable slot keys`() {val first=slot();val second=slot().copy(slotKey=UUID.randomUUID(),localTime=LocalTime.of(21,0));val result=assertIs<WeeklySeriesResult.Success>(service.create(actor,rule().copy(slots=listOf(first,second))));assertEquals(setOf(first.slotKey,second.slotKey),result.series.rule.slots.map{it.slotKey}.toSet());assertEquals(24,result.series.occurrences.size)}

    @Test fun `HTTP create returns created ETag and response-only resolved instants`() {val response=controller.create(ID,"$group",request());assertEquals(201,response.statusCode.value());assertEquals("\"1\"",response.headers.eTag);assertEquals(12,response.body!!.occurrences.size);assertNotNull(response.body!!.occurrences.first().startsAt)}
    @Test fun `HTTP retry returns OK with same bounded response`() {val request=request();controller.create(ID,"$group",request);val replay=controller.create(ID,"$group",request);assertEquals(200,replay.statusCode.value());assertEquals(12,replay.body!!.occurrences.size)}
    @Test fun `HTTP read round trips local rule and quoted ETag`() {val request=request();controller.create(ID,"$group",request);val response=controller.read(ID,"$group","${request.requestId}");assertEquals(request.zoneId,response.body!!.zoneId);assertEquals(request.slots!!.single().localTime,response.body!!.slots.single().localTime);assertEquals("\"1\"",response.headers.eTag)}
    @Test fun `HTTP create requires command and revision UUIDs`() {assertFailsWith<InvalidGroupRequestException>{controller.create(ID,"$group",request().copy(requestId=null))};assertFailsWith<InvalidGroupRequestException>{controller.create(ID,"$group",request().copy(revisionId=null))}}
    @Test fun `boundary requires explicit scope and action`() {val created=create();assertFailsWith<InvalidGroupRequestException>{controller.boundary(ID,"$group","${created.requestId}","\"1\"",SeriesBoundaryRequest(UUID.randomUUID(),null,SeriesBoundaryAction.CANCEL,UUID.randomUUID(),null,null))};assertFailsWith<InvalidGroupRequestException>{controller.boundary(ID,"$group","${created.requestId}","\"1\"",SeriesBoundaryRequest(UUID.randomUUID(),SeriesBoundaryScope.ONLY_THIS,null,UUID.randomUUID(),null,null))}}
    @Test fun `only this cancel delegates exact selected occurrence`() {val created=create();val game=repository.views.getValue(created.requestId!!).occurrences.first().id;controller.boundary(ID,"$group","${created.requestId}","\"1\"",SeriesBoundaryRequest(UUID.randomUUID(),SeriesBoundaryScope.ONLY_THIS,SeriesBoundaryAction.CANCEL,game,null,null));assertEquals(game,boundaryRepository.only!!.gameId);assertEquals(SeriesBoundaryAction.CANCEL,boundaryRepository.only!!.action)}
    @Test fun `only this edit requires valid replacement`() {val created=create();val game=repository.views.getValue(created.requestId!!).occurrences.first().id;assertFailsWith<InvalidGroupRequestException>{controller.boundary(ID,"$group","${created.requestId}","\"1\"",SeriesBoundaryRequest(UUID.randomUUID(),SeriesBoundaryScope.ONLY_THIS,SeriesBoundaryAction.EDIT,game,null,null))}}
    @Test fun `this and future delegates successor local boundary`() {val created=create();val old=repository.views.getValue(created.requestId!!);val successor=request().copy(requestId=created.requestId,revisionId=UUID.randomUUID(),localStartDate=DATE.plusWeeks(1));controller.boundary(ID,"$group","${created.requestId}","\"1\"",SeriesBoundaryRequest(UUID.randomUUID(),SeriesBoundaryScope.THIS_AND_FUTURE,SeriesBoundaryAction.EDIT,null,DATE.plusWeeks(1),old.rule.revisionId,successor));assertEquals(DATE.plusWeeks(1),boundaryRepository.future!!.boundary);assertEquals(successor.revisionId,boundaryRepository.future!!.successorRule.revisionId)}
    @Test fun `boundary requires quoted ETag before mutation`() {val created=create();assertFailsWith<PreconditionRequiredException>{controller.boundary(ID,"$group","${created.requestId}",null,SeriesBoundaryRequest(UUID.randomUUID(),SeriesBoundaryScope.ONLY_THIS,SeriesBoundaryAction.CANCEL,UUID.randomUUID(),null,null))};assertNull(boundaryRepository.only)}
    @Test fun `athlete boundary is forbidden before target probe`() {val created=create();repository.actorRole=GroupRole.ATHLETE;assertFailsWith<AccessForbiddenException>{controller.boundary(ID,"$group","${created.requestId}","\"1\"",SeriesBoundaryRequest(UUID.randomUUID(),SeriesBoundaryScope.ONLY_THIS,SeriesBoundaryAction.CANCEL,UUID.randomUUID(),null,null))};assertNull(boundaryRepository.only)}

    private fun create():WeeklySeriesWriteRequest=request().also{controller.create(ID,"$group",it)}
    private fun request():WeeklySeriesWriteRequest{val rule=rule();return WeeklySeriesWriteRequest(rule.seriesId,rule.revisionId,rule.zoneId,rule.localStartDate,rule.localEndDate,rule.slots.map{WeeklySlotRequest(it.slotKey,it.weekday,it.localTime,it.durationMinutes,GameVenueRequest(it.venue.venueId,it.venue.name,it.venue.address,it.venue.court),it.capacity,it.confirmationLeadMinutes,it.gameFeeCents,it.title)})}
    private fun rule()=WeeklySeriesRule(group,UUID.randomUUID(),UUID.randomUUID(),"America/Sao_Paulo",DATE,slots=listOf(slot()))
    private fun slot()=WeeklySlotRule(UUID.randomUUID(),DayOfWeek.WEDNESDAY,LocalTime.of(19,30),90,GameVenueSnapshot(null,"Arena Central","Rua das Flores 100","Quadra 2"),24,180,2500,"Treino semanal")
    private inner class MemorySeriesRepository:WeeklySeriesRepository{var actorRole:GroupRole?=GroupRole.OWNER;var createCalls=0;val views=mutableMapOf<UUID,WeeklySeriesView>();override fun role(actor:UUID,groupId:UUID)=if(groupId==group)actorRole else null;override fun create(rule:WeeklySeriesRule,occurrences:List<br.com.saqz.groups.application.game.recurrence.MaterializedGameOccurrence>):Boolean{createCalls++;if(rule.seriesId in views)return false;views[rule.seriesId]=WeeklySeriesView(rule,1,1,occurrences.map{SeriesOccurrenceView(it.id,it.occurrence.localDate,it.occurrence.localTime,it.occurrence.startsAt,it.status,1)});return true};override fun find(groupId:UUID,lineageId:UUID)=if(groupId==group)views[lineageId] else null}
    private class MemoryBoundaryRepository:SeriesBoundaryRepository{var only:OnlyThisBoundaryCommand?=null;var future:FutureBoundaryCommand?=null;override fun applyOnlyThis(command:OnlyThisBoundaryCommand):SeriesBoundaryResult{only=command;return SeriesBoundaryResult.Applied};override fun applyThisAndFuture(command:FutureBoundaryCommand):SeriesBoundaryResult{future=command;return SeriesBoundaryResult.Applied}}
    private companion object{val DATE=LocalDate.of(2026,8,12);val CLOCK=Clock.fixed(Instant.parse("2026-08-01T12:00:00Z"),ZoneOffset.UTC);val ID=RequestIdentity("subject",emailVerified=true,displayName="Player")}
}
