package br.com.saqz.groups.presentation.games.editor

import br.com.saqz.groups.data.game.*
import br.com.saqz.network.*
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.*
import kotlin.test.*

@OptIn(ExperimentalCoroutinesApi::class)
class GameEditorViewModelTest {
    @Test fun `new draft copies group defaults exactly once`()=runTest{val f=fixture(this);val form=f.vm.state.value.draft.form;assertEquals("Grupo",form.title);assertEquals("Arena",form.venue?.name);assertEquals("24",form.capacity);assertEquals("25,00",form.gameFeeBrl)}
    @Test fun `restored draft wins over changed current defaults`()=runTest{val restored=draft().copy(form=validForm().copy(title="Restored"),commandKey="restored");val f=fixture(this,stored=restored,defaults=defaults().copy(title="Changed"));assertEquals("Restored",f.vm.state.value.draft.form.title);assertEquals("restored",f.vm.state.value.draft.commandKey)}
    @Test fun `unsupported draft schema is ignored`()=runTest{val f=fixture(this,stored=draft().copy(schemaVersion=99,form=validForm().copy(title="Old")));assertEquals("Grupo",f.vm.state.value.draft.form.title)}
    @Test fun `mode and form changes persist together`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.SetMode(GameEditorMode.WEEKLY));f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(slots=listOf(slot()))));assertEquals(GameEditorMode.WEEKLY,f.store.writes.last().mode);assertEquals(1,f.store.writes.last().form.slots.size)}
    @Test fun `add slot uses injected stable identity and copied form defaults`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.AddSlot);val added=f.vm.state.value.draft.form.slots.single();assertEquals("stable-key",added.slotKey);assertEquals("Grupo",added.title);assertEquals("Arena",added.venue.name);assertEquals(24,added.capacity);assertEquals(2500,added.gameFeeCents)}
    @Test fun `one time validation reports every required and bounded field`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.UpdateForm(GameEditorForm(durationMinutes="2",capacity="1",gameFeeBrl="x",notes="x")));f.vm.onIntent(GameEditorIntent.Submit);assertTrue(f.vm.state.value.fieldErrors.keys.containsAll(listOf("title","venue","localDate","localTime","zoneId","startsAt","confirmationDeadline","durationMinutes","capacity","gameFeeBrl","notes")));assertEquals(0,f.gateway.calls.size)}
    @Test fun `weekly validation requires one slot`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.SetMode(GameEditorMode.WEEKLY));f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(slots=emptyList())));f.vm.onIntent(GameEditorIntent.Submit);assertEquals(listOf("must not be empty"),f.vm.state.value.fieldErrors["slots"])}
    @Test fun `BRL fee converts comma amount to integer cents`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(gameFeeBrl="12,34")));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertEquals(1234,f.gateway.gameCommands.single().gameFeeCents)}
    @Test fun `blank notes normalize to null`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(notes="  ")));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertNull(f.gateway.gameCommands.single().notes)}
    @Test fun `one time create retains stable command key`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.UpdateForm(validForm()));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertEquals("stable-key",f.gateway.gameCommands.single().requestId)}
    @Test fun `weekly create sends every local slot and optional end`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.SetMode(GameEditorMode.WEEKLY));f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(localEndDate="2026-12-31",slots=listOf(slot(),slot().copy(slotKey="slot-2")))));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertEquals(2,f.gateway.seriesCommands.single().slots?.size);assertEquals("2026-12-31",f.gateway.seriesCommands.single().localEndDate)}
    @Test fun `weekly edit refuses silent scope default`()=runTest{val f=fixture(this,existing=versionedGame(),series=versionedSeries());f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(slots=listOf(slot()))));f.vm.onIntent(GameEditorIntent.Submit);assertEquals(listOf("is required"),f.vm.state.value.fieldErrors["scope"]);assertTrue(f.gateway.boundaries.isEmpty())}
    @Test fun `only this edit carries replacement and original ETag`()=runTest{val f=fixture(this,existing=versionedGame(),series=versionedSeries());f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(slots=listOf(slot()))));f.vm.onIntent(GameEditorIntent.SetScope(SeriesBoundaryScopeDto.ONLY_THIS));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();val call=f.gateway.boundaries.single();assertEquals("\"7\"",call.etag);assertNotNull(call.command.replacement);assertNull(call.command.successor)}
    @Test fun `this and future edit carries successor and explicit boundary`()=runTest{val f=fixture(this,existing=versionedGame(),series=versionedSeries());f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(slots=listOf(slot()))));f.vm.onIntent(GameEditorIntent.SetScope(SeriesBoundaryScopeDto.THIS_AND_FUTURE));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();val command=f.gateway.boundaries.single().command;assertEquals("2026-08-12",command.boundary);assertNotNull(command.successor)}
    @Test fun `conflict preserves draft command key and offers reload`()=runTest{val f=fixture(this,existing=versionedGame(),gameResult=NetworkResult.Failure(problem("VERSION_CONFLICT",409)));f.vm.onIntent(GameEditorIntent.UpdateForm(validForm().copy(title="Unsaved")));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertEquals("Unsaved",f.vm.state.value.draft.form.title);assertEquals("stable-key",f.vm.state.value.draft.commandKey);assertTrue(f.vm.state.value.reloadAvailable)}
    @Test fun `validation response preserves draft and indexed errors`()=runTest{val failure=NetworkResult.Failure(NetworkError.ApiProblemError(ApiProblem(400,"VALIDATION_FAILED","c",mapOf("slots[0].weekday" to listOf("bad")))));val f=fixture(this,gameResult=failure);f.vm.onIntent(GameEditorIntent.UpdateForm(validForm()));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertEquals(listOf("bad"),f.vm.state.value.fieldErrors["slots[0].weekday"]);assertEquals(validForm(),f.vm.state.value.draft.form)}
    @Test fun `reload effect targets authoritative existing game`()=runTest{val f=fixture(this,existing=versionedGame(),gameResult=NetworkResult.Failure(problem("VERSION_CONFLICT",409)));f.vm.onIntent(GameEditorIntent.UpdateForm(validForm()));f.vm.onIntent(GameEditorIntent.Submit);runCurrent();val effect=async{f.vm.effects.first()};f.vm.onIntent(GameEditorIntent.Reload);assertEquals(GameEditorEffect.Reload(GROUP,GAME),effect.await())}
    @Test fun `duplicate submit is single flight`()=runTest{val f=fixture(this);f.gateway.gate=CompletableDeferred();f.vm.onIntent(GameEditorIntent.UpdateForm(validForm()));f.vm.onIntent(GameEditorIntent.Submit);f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertEquals(1,f.gateway.calls.size);f.gateway.gate!!.complete(Unit);runCurrent()}
    @Test fun `success clears matching draft and emits saved once`()=runTest{val f=fixture(this);f.vm.onIntent(GameEditorIntent.UpdateForm(validForm()));val effect=async{f.vm.effects.first()};f.vm.onIntent(GameEditorIntent.Submit);runCurrent();assertEquals(GameEditorEffect.Saved(GAME),effect.await());assertEquals("stable-key",f.store.clears.single().third);assertEquals(GAME,f.vm.state.value.successId)}

    private fun fixture(scope:CoroutineScope,stored:GameEditorDraft?=null,defaults:GameEditorDefaults=defaults(),existing:VersionedGameDto?=null,series:VersionedSeriesDto?=null,gameResult:NetworkResult<VersionedGameDto> = NetworkResult.Success(versionedGame())):Fixture{val gateway=FakeGateway(gameResult);val store=FakeStore(stored);val vm=GameEditorViewModel(GameEditorInput(GROUP,defaults,existing,series),gateway,store,GameCommandKeyFactory{"stable-key"},scope);return Fixture(vm,gateway,store)}
    private fun defaults()=GameEditorDefaults("Grupo",GameVenueDto(null,"Arena","Rua Central 100"),"America/Sao_Paulo",90,24,180,2500)
    private fun validForm()=GameEditorForm("Treino",GameVenueDto(null,"Arena","Rua Central 100"),"2026-08-12","19:30:00","America/Sao_Paulo","2026-08-12T22:30:00Z","90","24","2026-08-12T19:30:00Z","25,00","Notas")
    private fun slot()=WeeklySlotDto("slot-1",WeekdayDto.WEDNESDAY,"19:30:00",90,GameVenueDto(null,"Arena","Rua Central 100"),24,180,2500,"Treino")
    private fun draft()=GameEditorDraft(groupId=GROUP,gameId=null,seriesId=null,commandKey="old",etag=null,mode=GameEditorMode.ONE_TIME,form=validForm())
    private fun versionedGame()=VersionedGameDto(GameDto(GAME,GROUP,"Treino",GameVenueDto(null,"Arena","Rua Central 100"),"2026-08-12","19:30:00","America/Sao_Paulo","2026-08-12T22:30:00Z",90,24,"2026-08-12T19:30:00Z",2500,"Notas",GameStatusDto.DRAFT,7,0,24,0),"\"7\"")
    private fun versionedSeries()=VersionedSeriesDto(WeeklySeriesDto(SERIES,"revision",1,"America/Sao_Paulo","2026-08-12",slots=listOf(slot()),occurrences=emptyList(),version=7),"\"7\"")
    private fun problem(code:String,status:Int)=NetworkError.ApiProblemError(ApiProblem(status,code,"c"))
    private class FakeStore(private val stored:GameEditorDraft?):GameDraftStorePort{val writes=mutableListOf<GameEditorDraft>();val clears=mutableListOf<Triple<String,String?,String>>();override fun read(groupId:String,resourceId:String?,done:(GameDraftReadResult)->Unit)=done(GameDraftReadResult.Success(stored));override fun write(draft:GameEditorDraft,done:(GameDraftWriteResult)->Unit){writes+=draft;done(GameDraftWriteResult.Success)};override fun clear(groupId:String,resourceId:String?,commandKey:String,done:(GameDraftWriteResult)->Unit){clears+=Triple(groupId,resourceId,commandKey);done(GameDraftWriteResult.Success)}}
    private data class Boundary(val etag:String,val command:SeriesBoundaryCommand)
    private inner class FakeGateway(var gameResult:NetworkResult<VersionedGameDto>):GameGateway{val calls=mutableListOf<String>();val gameCommands=mutableListOf<GameWriteCommand>();val seriesCommands=mutableListOf<WeeklySeriesWriteCommand>();val boundaries=mutableListOf<Boundary>();var gate:CompletableDeferred<Unit>?=null;override suspend fun list(groupId:String)=error("unused");override suspend fun read(groupId:String,gameId:String)=gameResult;override suspend fun create(groupId:String,command:GameWriteCommand):NetworkResult<VersionedGameDto>{calls+="create";gameCommands+=command;gate?.await();return gameResult};override suspend fun edit(groupId:String,gameId:String,etag:String,command:GameWriteCommand):NetworkResult<VersionedGameDto>{calls+="edit";gameCommands+=command;gate?.await();return gameResult};override suspend fun lifecycle(groupId:String,gameId:String,etag:String,command:String)=gameResult;override suspend fun createSeries(groupId:String,command:WeeklySeriesWriteCommand):NetworkResult<VersionedSeriesDto>{calls+="series";seriesCommands+=command;return NetworkResult.Success(versionedSeries())};override suspend fun readSeries(groupId:String,seriesId:String)=NetworkResult.Success(versionedSeries());override suspend fun boundary(groupId:String,seriesId:String,etag:String,command:SeriesBoundaryCommand):NetworkResult<VersionedSeriesDto>{calls+="boundary";boundaries+=Boundary(etag,command);return NetworkResult.Success(versionedSeries())}}
    private data class Fixture(val vm:GameEditorViewModel,val gateway:FakeGateway,val store:FakeStore)
    private companion object{const val GROUP="group";const val GAME="game";const val SERIES="series"}
}
