package br.com.saqz.groups.presentation.games.detail

import br.com.saqz.groups.data.GroupRoleDto
import br.com.saqz.groups.data.attendance.*
import br.com.saqz.groups.data.attendance.share.*
import br.com.saqz.groups.data.game.*
import br.com.saqz.groups.presentation.attendance.share.AttendanceShareImageModel
import br.com.saqz.network.*
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.async
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.*
import kotlinx.datetime.Instant
import kotlin.test.*

@OptIn(ExperimentalCoroutinesApi::class)
class GameDetailAttendanceViewModelTest {
    @Test fun `no response exposes authoritative counts and confirm decline actions`()=runTest{val f=fixture(this);runCurrent();assertEquals(setOf(AttendanceAction.CONFIRM,AttendanceAction.DECLINE),f.vm.state.value.attendanceActions);assertEquals(2,f.vm.state.value.confirmedCount);assertEquals(1,f.vm.state.value.availableSpots)}
    @Test fun `confirmed response exposes withdrawal only`()=runTest{val f=fixture(this,detail=detail(AttendanceStatusDto.CONFIRMED));runCurrent();assertEquals(setOf(AttendanceAction.WITHDRAW),f.vm.state.value.attendanceActions)}
    @Test fun `waitlisted response exposes stable position and withdrawal`()=runTest{val f=fixture(this,detail=detail(AttendanceStatusDto.WAITLISTED,4));runCurrent();assertEquals(4,f.vm.state.value.waitlistPosition);assertEquals(setOf(AttendanceAction.WITHDRAW),f.vm.state.value.attendanceActions)}
    @Test fun `declined response may confirm again`()=runTest{val f=fixture(this,detail=detail(AttendanceStatusDto.DECLINED));runCurrent();assertEquals(setOf(AttendanceAction.CONFIRM),f.vm.state.value.attendanceActions)}
    @Test fun `deadline closes athlete actions`()=runTest{val f=fixture(this,game=versioned(deadline="2026-07-31T10:00:00Z"));runCurrent();assertTrue(f.vm.state.value.attendanceActions.isEmpty())}
    @Test fun `cancelled game freezes athlete actions`()=runTest{val f=fixture(this,game=versioned(status=GameStatusDto.CANCELLED));runCurrent();assertTrue(f.vm.state.value.attendanceActions.isEmpty())}
    @Test fun `withdrawal confirmation explicitly marks pending charge`()=runTest{val f=fixture(this,detail=detail(AttendanceStatusDto.CONFIRMED));runCurrent();f.vm.onIntent(GameDetailIntent.RequestAttendance(AttendanceAction.WITHDRAW));assertTrue(f.vm.state.value.withdrawalKeepsCharge);assertTrue(f.attendance.respondCalls.isEmpty())}
    @Test fun `confirmed attendance sends stable command key and exact intent`()=runTest{val f=fixture(this);runCurrent();f.vm.onIntent(GameDetailIntent.RequestAttendance(AttendanceAction.CONFIRM));f.vm.onIntent(GameDetailIntent.ConfirmAttendance);runCurrent();assertEquals(SelfCall(KEY,AttendanceIntentDto.CONFIRM),f.attendance.respondCalls.single())}
    @Test fun `double tap is one logical attendance command`()=runTest{val f=fixture(this);runCurrent();f.attendance.gate=CompletableDeferred();f.vm.onIntent(GameDetailIntent.RequestAttendance(AttendanceAction.CONFIRM));f.vm.onIntent(GameDetailIntent.ConfirmAttendance);f.vm.onIntent(GameDetailIntent.ConfirmAttendance);runCurrent();assertEquals(1,f.attendance.respondCalls.size);f.attendance.gate!!.complete(Unit);runCurrent()}
    @Test fun `pending response never optimistically claims capacity`()=runTest{val f=fixture(this);runCurrent();f.attendance.gate=CompletableDeferred();f.attendance.respondResult=mutation(AttendanceStatusDto.WAITLISTED,position=3,confirmed=3,available=0);f.vm.onIntent(GameDetailIntent.RequestAttendance(AttendanceAction.CONFIRM));f.vm.onIntent(GameDetailIntent.ConfirmAttendance);runCurrent();assertNull(f.vm.state.value.ownAttendance);assertEquals(1,f.vm.state.value.availableSpots);f.attendance.gate!!.complete(Unit);runCurrent();assertEquals(AttendanceStatusDto.WAITLISTED,f.vm.state.value.ownAttendance!!.status);assertEquals(0,f.vm.state.value.availableSpots)}
    @Test fun `conflict preserves logical command for same key retry`()=runTest{val f=fixture(this);runCurrent();f.attendance.respondResult=NetworkResult.Failure(problem("VERSION_CONFLICT",409));f.vm.onIntent(GameDetailIntent.RequestAttendance(AttendanceAction.CONFIRM));f.vm.onIntent(GameDetailIntent.ConfirmAttendance);runCurrent();assertEquals(GameDetailError.CONFLICT,f.vm.state.value.attendanceError);assertTrue(f.vm.state.value.retryAttendanceAvailable);f.attendance.respondResult=mutation(AttendanceStatusDto.CONFIRMED);f.vm.onIntent(GameDetailIntent.RetryAttendance);runCurrent();assertEquals(listOf(KEY,KEY),f.attendance.respondCalls.map{it.key})}
    @Test fun `promotion refresh replaces waitlist with authoritative confirmation`()=runTest{val f=fixture(this,detail=detail(AttendanceStatusDto.WAITLISTED,1));runCurrent();f.attendance.readResult=NetworkResult.Success(detail(AttendanceStatusDto.CONFIRMED));f.vm.onIntent(GameDetailIntent.RefreshAttendance);runCurrent();assertEquals(AttendanceStatusDto.CONFIRMED,f.vm.state.value.ownAttendance!!.status);assertNull(f.vm.state.value.waitlistPosition)}
    @Test fun `attendance success emits charge refresh effect once`()=runTest{val f=fixture(this);runCurrent();val effect=async{f.vm.effects.first()};f.vm.onIntent(GameDetailIntent.RequestAttendance(AttendanceAction.CONFIRM));f.vm.onIntent(GameDetailIntent.ConfirmAttendance);runCurrent();assertEquals(GameDetailEffect.AttendanceApplied(AttendanceStatusDto.CONFIRMED,0,true),effect.await())}
    @Test fun `organizer override validates member and reason locally`()=runTest{val f=fixture(this,role=GroupRoleDto.OWNER);runCurrent();f.vm.onIntent(GameDetailIntent.OverrideAttendance("",AttendanceIntentDto.CONFIRM,"x"));assertEquals(GameDetailError.VALIDATION,f.vm.state.value.attendanceError);assertTrue(f.attendance.overrideCalls.isEmpty())}
    @Test fun `organizer override sends explicit target reason and stable key`()=runTest{val f=fixture(this,role=GroupRoleDto.ADMIN);runCurrent();f.vm.onIntent(GameDetailIntent.OverrideAttendance("member-2",AttendanceIntentDto.DECLINE,"  Correção manual  "));runCurrent();assertEquals(OverrideCall(KEY,"member-2",AttendanceIntentDto.DECLINE,"Correção manual"),f.attendance.overrideCalls.single())}
    @Test fun `athlete cannot send organizer override`()=runTest{val f=fixture(this,role=GroupRoleDto.ATHLETE);runCurrent();f.vm.onIntent(GameDetailIntent.OverrideAttendance("member-2",AttendanceIntentDto.CONFIRM,"Ajuste"));runCurrent();assertTrue(f.attendance.overrideCalls.isEmpty())}
    @Test fun `capacity conflict preserves value etag and key for retry`()=runTest{val f=fixture(this,role=GroupRoleDto.OWNER);runCurrent();f.attendance.capacityResult=NetworkResult.Failure(problem("VERSION_CONFLICT",409));f.vm.onIntent(GameDetailIntent.ChangeCapacity(30));runCurrent();f.attendance.capacityResult=capacity(30);f.vm.onIntent(GameDetailIntent.RetryAttendance);runCurrent();assertEquals(listOf(CapacityCall(KEY,30,"\"7\""),CapacityCall(KEY,30,"\"7\"")),f.attendance.capacityCalls)}
    @Test fun `capacity success updates etag counts and emits promotion`()=runTest{val f=fixture(this,role=GroupRoleDto.OWNER);runCurrent();f.attendance.capacityResult=capacity(30,promoted=2);val effect=async{f.vm.effects.first()};f.vm.onIntent(GameDetailIntent.ChangeCapacity(30));runCurrent();assertEquals("\"8\"",f.vm.state.value.etag);assertEquals(30,f.vm.state.value.game!!.capacity);assertEquals(GameDetailEffect.CapacityApplied(30,2),effect.await())}
    @Test fun `organizer rotates attendance link and emits share effect`()=runTest{val f=fixture(this,role=GroupRoleDto.OWNER);runCurrent();val effect=async{f.vm.effects.first()};f.vm.onIntent(GameDetailIntent.RequestAttendanceLinkShare);runCurrent();assertEquals(ShareLinkCall("group","game"),f.share.rotateCalls.single());assertEquals(GameDetailEffect.ShareAttendanceLink(LINK_URL),effect.await());assertEquals(LINK_URL,f.vm.state.value.attendanceLinkUrl)}
    @Test fun `attendance link retry reuses cached url without network`()=runTest{val f=fixture(this,role=GroupRoleDto.OWNER);runCurrent();f.vm.onIntent(GameDetailIntent.RequestAttendanceLinkShare);runCurrent();f.share.rotateCalls.clear();val effect=async{f.vm.effects.first()};f.vm.onIntent(GameDetailIntent.RetryAttendanceLinkShare);runCurrent();assertTrue(f.share.rotateCalls.isEmpty());assertEquals(GameDetailEffect.ShareAttendanceLink(LINK_URL),effect.await())}
    @Test fun `organizer snapshot loads privacy confirmation before share effect`()=runTest{val f=fixture(this,role=GroupRoleDto.OWNER);runCurrent();f.vm.onIntent(GameDetailIntent.RequestAttendanceImageShare);runCurrent();assertEquals(ShareSnapshotCall("group","game"),f.share.snapshotCalls.single());assertTrue(f.vm.state.value.showAttendanceSharePrivacy);assertNotNull(f.vm.state.value.attendanceShareSnapshot)}
    @Test fun `confirming privacy emits image share effect`()=runTest{val f=fixture(this,role=GroupRoleDto.OWNER);runCurrent();f.vm.onIntent(GameDetailIntent.RequestAttendanceImageShare);runCurrent();val effect=async{f.vm.effects.first()};f.vm.onIntent(GameDetailIntent.ConfirmAttendanceImageShare);runCurrent();assertIs<GameDetailEffect.ShareAttendanceImage>(effect.await())}
    @Test fun `athlete never starts organizer share operations`()=runTest{val f=fixture(this,role=GroupRoleDto.ATHLETE);runCurrent();f.vm.onIntent(GameDetailIntent.RequestAttendanceLinkShare);f.vm.onIntent(GameDetailIntent.RequestAttendanceImageShare);runCurrent();assertTrue(f.share.rotateCalls.isEmpty());assertTrue(f.share.snapshotCalls.isEmpty())}

    private fun fixture(scope:kotlinx.coroutines.CoroutineScope,role:GroupRoleDto=GroupRoleDto.ATHLETE,detail:AttendanceDetailDto=detail(),game:VersionedGameDto=versioned()):Fixture{val games=FakeGames(game);val attendance=FakeAttendance(NetworkResult.Success(detail));val share=FakeAttendanceShare();val vm=GameDetailViewModel(games,"group","game",role,scope,attendance,share,AttendanceCommandKeyFactory{KEY},{NOW});return Fixture(vm,attendance,share)}
    private fun detail(status:AttendanceStatusDto?=null,position:Long?=null,confirmed:Int=2,available:Int=1)=AttendanceDetailDto(status?.let{AttendanceEntryDto("member",it,position,1)},confirmed,available,if(status==AttendanceStatusDto.WAITLISTED)1 else 0,3)
    private fun mutation(status:AttendanceStatusDto,position:Long?=null,confirmed:Int=3,available:Int=0)=NetworkResult.Success(VersionedAttendanceMutationDto(AttendanceMutationDto(AttendanceEntryDto("member",status,position,2),null,0,detail(status,position,confirmed,available)),"\"2\""))
    private fun capacity(value:Int,promoted:Int=0)=NetworkResult.Success(VersionedCapacityDto(CapacityDto(value,8,promoted,AttendanceDetailDto(null,3,value-3,0,value)),"\"8\""))
    private fun versioned(status:GameStatusDto=GameStatusDto.PUBLISHED,deadline:String="2026-08-12T19:00:00Z")=VersionedGameDto(GameDto("game","group","Treino",GameVenueDto(null,"Arena","Rua 1"),"2026-08-12","19:30:00","America/Sao_Paulo","2026-08-12T22:30:00Z",90,3,deadline,2500,"Notas",status,7,2,1,0,false),"\"7\"")
    private fun problem(code:String,status:Int)=NetworkError.ApiProblemError(ApiProblem(status,code,"c"))
    private data class SelfCall(val key:String,val intent:AttendanceIntentDto)
    private data class OverrideCall(val key:String,val member:String,val intent:AttendanceIntentDto,val reason:String)
    private data class CapacityCall(val key:String,val capacity:Int,val etag:String)
    private data class ShareLinkCall(val groupId:String,val gameId:String)
    private data class ShareSnapshotCall(val groupId:String,val gameId:String)
    private inner class FakeAttendance(var readResult:NetworkResult<AttendanceDetailDto>):AttendanceGateway{val respondCalls=mutableListOf<SelfCall>();val overrideCalls=mutableListOf<OverrideCall>();val capacityCalls=mutableListOf<CapacityCall>();var respondResult:NetworkResult<VersionedAttendanceMutationDto> = mutation(AttendanceStatusDto.CONFIRMED);var overrideResult:NetworkResult<VersionedAttendanceMutationDto> = mutation(AttendanceStatusDto.CONFIRMED);var capacityResult:NetworkResult<VersionedCapacityDto> = capacity(3);var gate:CompletableDeferred<Unit>?=null;override suspend fun read(groupId:String,gameId:String)=readResult;override suspend fun respond(groupId:String,gameId:String,command:SelfAttendanceCommand):NetworkResult<VersionedAttendanceMutationDto>{respondCalls+=SelfCall(command.requestId,command.intent);gate?.await();return respondResult};override suspend fun override(groupId:String,gameId:String,command:OverrideAttendanceCommand):NetworkResult<VersionedAttendanceMutationDto>{overrideCalls+=OverrideCall(command.requestId,command.memberId,command.intent,command.reason);return overrideResult};override suspend fun capacity(groupId:String,gameId:String,etag:String,command:CapacityCommand):NetworkResult<VersionedCapacityDto>{capacityCalls+=CapacityCall(command.requestId,command.capacity,etag);return capacityResult}}
    private class FakeGames(private val initial:VersionedGameDto):GameGateway{override suspend fun read(groupId:String,gameId:String)=NetworkResult.Success(initial);override suspend fun list(groupId:String)=error("unused");override suspend fun create(groupId:String,command:GameWriteCommand)=error("unused");override suspend fun edit(groupId:String,gameId:String,etag:String,command:GameWriteCommand)=error("unused");override suspend fun lifecycle(groupId:String,gameId:String,etag:String,mutation:String)=error("unused");override suspend fun createSeries(groupId:String,command:WeeklySeriesWriteCommand)=error("unused");override suspend fun readSeries(groupId:String,seriesId:String)=error("unused");override suspend fun boundary(groupId:String,seriesId:String,etag:String,command:SeriesBoundaryCommand)=error("unused")}
    private inner class FakeAttendanceShare:AttendanceShareGateway{val rotateCalls=mutableListOf<ShareLinkCall>();val snapshotCalls=mutableListOf<ShareSnapshotCall>();override suspend fun rotateLink(groupId:String,gameId:String)=NetworkResult.Success(AttendanceLinkUrlDto(LINK_URL)).also{rotateCalls+=ShareLinkCall(groupId,gameId)};override suspend fun resolveLink(code:String)=error("unused");override suspend fun readSnapshot(groupId:String,gameId:String)=NetworkResult.Success(snapshot()).also{snapshotCalls+=ShareSnapshotCall(groupId,gameId)}}
    private fun snapshot()=AttendanceShareSnapshotDto("Treino","2026-08-12T22:30:00Z","America/Sao_Paulo","Arena",3,listOf(AttendanceShareSnapshotPersonDto("Ana")),listOf(AttendanceShareSnapshotPersonDto("Bruno",1)),listOf(AttendanceShareSnapshotPersonDto("Carla")))
    private data class Fixture(val vm:GameDetailViewModel,val attendance:FakeAttendance,val share:FakeAttendanceShare)
    private companion object{const val KEY="stable-attendance-key";const val LINK_URL="https://join.example.test/?saqz_attendance=abc";val NOW:Instant=Instant.parse("2026-08-01T10:00:00Z")}
}
