-- Durable reservation state for purchase-information e-mail delivery (VUL-212).
-- The recipient is deliberately not persisted: every actual send resolves it from
-- access_users, while this row serializes attempts per account.
CREATE TABLE subscription_purchase_information_emails (
    user_id uuid PRIMARY KEY,
    reservation_id uuid,
    reservation_created_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT fk_subscription_purchase_information_emails_user
        FOREIGN KEY (user_id) REFERENCES access_users (id) ON DELETE CASCADE,
    CONSTRAINT ck_subscription_purchase_information_emails_reservation_pair
        CHECK ((reservation_id IS NULL) = (reservation_created_at IS NULL))
);

CREATE INDEX ix_subscription_purchase_information_emails_stale_reservation
    ON subscription_purchase_information_emails (reservation_created_at)
    WHERE reservation_id IS NOT NULL;

-- Successful SMTP acceptances are the only events that consume the three-per-hour
-- quota. Keeping one row per success makes the limit a strict rolling window rather
-- than a fixed bucket anchored to the first success.
CREATE TABLE subscription_purchase_information_email_successes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    succeeded_at timestamptz NOT NULL,
    CONSTRAINT fk_subscription_purchase_information_email_successes_user
        FOREIGN KEY (user_id) REFERENCES access_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_subscription_purchase_information_email_successes_user_time
    ON subscription_purchase_information_email_successes (user_id, succeeded_at);
