package br.com.saqz.groups.presentation.finance.charges

import br.com.saqz.groups.data.*
import br.com.saqz.groups.data.finance.*
import br.com.saqz.network.*
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.async
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.*
import kotlin.test.*

@OptIn(ExperimentalCoroutinesApi::class)
class FinanceViewModelTest {
    @Test fun `athlete loads only own charges without totals members or draft`()=runTest{val f=fixture(this,role=GroupRoleDto.ATHLETE);runCurrent();assertEquals(1,f.athlete.calls);assertEquals(0,f.organizer.chargeCalls);assertNull(f.vm.state.value.totals);assertTrue(f.vm.state.value.members.isEmpty());assertNull(f.vm.state.value.monthlyDraft);assertEquals(0,f.store.reads)}
    @Test fun `athlete cannot dispatch monthly status or retry commands`()=runTest{val f=fixture(this,role=GroupRoleDto.ATHLETE);runCurrent();f.vm.onIntent(FinanceIntent.UpdateMonthly("2026-08","70,00","2026-08-10",setOf(MEMBER)));f.vm.onIntent(FinanceIntent.UpdateStatus(CHARGE,ChargeStatusDto.PAID));f.vm.onIntent(FinanceIntent.GenerateMonthly);f.vm.onIntent(FinanceIntent.Retry);runCurrent();assertTrue(f.organizer.monthlyCalls.isEmpty());assertTrue(f.organizer.statusCalls.isEmpty());assertEquals(0,f.store.writes.size)}
    @Test fun `owner loads full charges totals and memberships without own route`()=runTest{val f=fixture(this);runCurrent();val state=f.vm.state.value;assertEquals(0,f.athlete.calls);assertEquals(1,f.organizer.chargeCalls);assertEquals(2,state.members.size);assertEquals(ChargeTotalsState(2500,5000,1000,7000),state.totals);assertEquals(2,state.charges.size)}
    @Test fun `admin has organizer charge capabilities`()=runTest{val f=fixture(this,role=GroupRoleDto.ADMIN);runCurrent();assertTrue(f.vm.state.value.organizer);assertEquals(1,f.organizer.chargeCalls);assertEquals(1,f.memberships.calls)}
    @Test fun `matching versioned monthly draft restores exact key and selection`()=runTest{val restored=draft(reviewed=true);val f=fixture(this,restored=restored);runCurrent();assertEquals(restored,f.vm.state.value.monthlyDraft)}
    @Test fun `foreign or unsupported draft never restores or dispatches`()=runTest{val f=fixture(this,restored=draft().copy(schemaVersion=99,groupId="other"));runCurrent();assertNull(f.vm.state.value.monthlyDraft);assertTrue(f.organizer.monthlyCalls.isEmpty())}
    @Test fun `monthly update filters inactive identifiers and persists stable key`()=runTest{val f=fixture(this);runCurrent();f.vm.onIntent(FinanceIntent.UpdateMonthly("2026-08","70,00","2026-08-10",setOf(MEMBER,"removed")));val value=f.vm.state.value.monthlyDraft!!;assertEquals(KEY,value.commandKey);assertEquals(setOf(MEMBER),value.selectedMemberIds);assertEquals(value,f.store.writes.single())}
    @Test fun `monthly edits retain one command key and reset review`()=runTest{val f=fixture(this);runCurrent();f.vm.onIntent(update());f.vm.onIntent(FinanceIntent.ReviewMonthly);f.vm.onIntent(update(amount="80,00"));assertEquals(listOf(KEY,KEY,KEY),f.store.writes.map{it.commandKey});assertFalse(f.vm.state.value.monthlyDraft!!.reviewed)}
    @Test fun `monthly review reports month amount date and member errors`()=runTest{val f=fixture(this);runCurrent();f.vm.onIntent(FinanceIntent.UpdateMonthly("2026-13","0","bad",emptySet()));f.vm.onIntent(FinanceIntent.ReviewMonthly);assertEquals(setOf("month","amountBrl","dueDate","memberIds"),f.vm.state.value.fieldErrors.keys);assertEquals(FinanceError.VALIDATION,f.vm.state.value.error)}
    @Test fun `valid monthly review persists reviewed draft without generating`()=runTest{val f=fixture(this);runCurrent();f.vm.onIntent(update());f.vm.onIntent(FinanceIntent.ReviewMonthly);assertTrue(f.vm.state.value.monthlyDraft!!.reviewed);assertEquals(2,f.store.writes.size);assertTrue(f.organizer.monthlyCalls.isEmpty())}
    @Test fun `monthly generation requires reviewed draft`()=runTest{val f=fixture(this);runCurrent();f.vm.onIntent(update());f.vm.onIntent(FinanceIntent.GenerateMonthly);runCurrent();assertTrue(f.organizer.monthlyCalls.isEmpty())}
    @Test fun `double generate is one logical stable command`()=runTest{val f=fixture(this);runCurrent();review(f);f.organizer.gate=CompletableDeferred();f.vm.onIntent(FinanceIntent.GenerateMonthly);f.vm.onIntent(FinanceIntent.GenerateMonthly);runCurrent();assertEquals(1,f.organizer.monthlyCalls.size);f.organizer.gate!!.complete(Unit);runCurrent()}
    @Test fun `generation sends exact cents members and key then clears matching draft`()=runTest{val f=fixture(this);runCurrent();review(f);val effect=async{f.vm.effects.first()};f.vm.onIntent(FinanceIntent.GenerateMonthly);runCurrent();assertEquals(MonthlyChargeCommandDto(KEY,"2026-08",7000,"2026-08-10",setOf(MEMBER,MEMBER2)),f.organizer.monthlyCalls.single());assertEquals(listOf(GROUP to KEY),f.store.clears);assertNull(f.vm.state.value.monthlyDraft);assertEquals("Cobranças registradas manualmente.",f.vm.state.value.lastManualOutcome);assertEquals(FinanceEffect.MonthlyGenerated(1),effect.await())}
    @Test fun `generation refreshes authoritative full charges and totals`()=runTest{val f=fixture(this);runCurrent();review(f);f.vm.onIntent(FinanceIntent.GenerateMonthly);runCurrent();assertEquals(2,f.organizer.chargeCalls);assertEquals(2,f.vm.state.value.charges.size);assertEquals(2500,f.vm.state.value.totals!!.pendingCents)}
    @Test fun `status command derives and preserves quoted charge version ETag`()=runTest{val f=fixture(this);runCurrent();f.vm.onIntent(FinanceIntent.UpdateStatus(CHARGE,ChargeStatusDto.WAIVED,"  Ajuste manual  "));runCurrent();assertEquals(StatusCall(CHARGE,"\"4\"",ChargeStatusCommandDto(ChargeStatusDto.WAIVED,"Ajuste manual")),f.organizer.statusCalls.single())}
    @Test fun `status success uses authoritative audit without editing amount actor or time`()=runTest{val f=fixture(this);runCurrent();val effect=async{f.vm.effects.first()};f.vm.onIntent(FinanceIntent.UpdateStatus(CHARGE,ChargeStatusDto.PAID));runCurrent();val updated=f.vm.state.value.charges.first{it.id==CHARGE};assertEquals(2500,updated.amountCents);assertEquals("actor",updated.events.single().actorId);assertEquals("2026-08-12T10:00:00Z",updated.events.single().occurredAt);assertEquals("Status registrado manualmente no histórico.",f.vm.state.value.lastManualOutcome);assertEquals(FinanceEffect.StatusRecorded(CHARGE,ChargeStatusDto.PAID),effect.await())}
    @Test fun `status conflict preserves exact ETag and command for retry`()=runTest{val f=fixture(this);runCurrent();f.organizer.statusResult=NetworkResult.Failure(problem("VERSION_CONFLICT",409));f.vm.onIntent(FinanceIntent.UpdateStatus(CHARGE,ChargeStatusDto.PAID));runCurrent();assertEquals(FinanceError.CONFLICT,f.vm.state.value.error);assertTrue(f.vm.state.value.reloadAvailable);f.organizer.statusResult=NetworkResult.Success(VersionedChargeDto(paidCharge(),"\"5\""));f.vm.onIntent(FinanceIntent.Retry);runCurrent();assertEquals(listOf("\"4\"","\"4\""),f.organizer.statusCalls.map{it.etag})}
    @Test fun `server validation fields survive status failure`()=runTest{val f=fixture(this);runCurrent();f.organizer.statusResult=NetworkResult.Failure(problem("VALIDATION_FAILED",400,mapOf("note" to listOf("is invalid"))));f.vm.onIntent(FinanceIntent.UpdateStatus(CHARGE,ChargeStatusDto.WAIVED,"x"));runCurrent();assertEquals(mapOf("note" to listOf("is invalid")),f.vm.state.value.fieldErrors)}
    @Test fun `draft write failure is typed without changing stable draft`()=runTest{val f=fixture(this);runCurrent();f.store.failWrites=true;f.vm.onIntent(update());assertEquals(FinanceError.DRAFT_UNAVAILABLE,f.vm.state.value.error);assertEquals(KEY,f.vm.state.value.monthlyDraft!!.commandKey)}
    @Test fun `state copy always identifies manual tracking and avoids settlement claim`()=runTest{val f=fixture(this,role=GroupRoleDto.ATHLETE);runCurrent();val copy=f.vm.state.value.manualTrackingNotice;assertEquals("Controle manual: nenhum pagamento é processado pelo app.",copy);assertFalse(copy.contains("liquidado",true));assertFalse(copy.contains("saldo",true))}

    private fun fixture(scope:kotlinx.coroutines.CoroutineScope,role:GroupRoleDto=GroupRoleDto.OWNER,restored:MonthlyChargeDraft?=null):Fixture{val athlete=FakeAthlete();val organizer=FakeOrganizer();val members=FakeMemberships();val store=FakeStore(restored);val vm=FinanceViewModel(GROUP,role,athlete,organizer,members,store,FinanceCommandKeyFactory{KEY},scope);return Fixture(vm,athlete,organizer,members,store)}
    private fun update(amount:String="70,00")=FinanceIntent.UpdateMonthly("2026-08",amount,"2026-08-10",setOf(MEMBER,MEMBER2))
    private fun draft(reviewed:Boolean=false)=MonthlyChargeDraft(groupId=GROUP,commandKey=KEY,month="2026-08",amountBrl="70,00",dueDate="2026-08-10",selectedMemberIds=setOf(MEMBER,MEMBER2),reviewed=reviewed)
    private fun review(f:Fixture){f.vm.onIntent(update());f.vm.onIntent(FinanceIntent.ReviewMonthly)}
    private fun charges()=ChargeListDto(listOf(charge(),charge("charge-2",MEMBER2)),2500,5000,1000,7000)
    private fun charge(id:String=CHARGE,member:String=MEMBER,status:ChargeStatusDto=ChargeStatusDto.PENDING,version:Long=4,events:List<ChargeEventDto> = emptyList())=ChargeDto(id,GROUP,member,ChargeKindDto.GAME,"game",null,2500,"2026-08-12",status,false,version,events)
    private fun paidCharge()=charge(status=ChargeStatusDto.PAID,version=5,events=listOf(ChargeEventDto("actor",ChargeStatusDto.PENDING,ChargeStatusDto.PAID,null,"2026-08-12T10:00:00Z")))
    private fun problem(code:String,status:Int,fields:Map<String,List<String>>?=null)=NetworkError.ApiProblemError(ApiProblem(status,code,"c",fields))
    private data class Fixture(val vm:FinanceViewModel,val athlete:FakeAthlete,val organizer:FakeOrganizer,val memberships:FakeMemberships,val store:FakeStore)
    private data class StatusCall(val chargeId:String,val etag:String,val command:ChargeStatusCommandDto)
    private class FakeAthlete:AthleteFinanceGateway{var calls=0;override suspend fun ownCharges(groupId:String):NetworkResult<ChargeListDto>{calls++;return NetworkResult.Success(ChargeListDto(listOf(chargeStatic())))}}
    private class FakeOrganizer:OrganizerFinanceGateway{var chargeCalls=0;val monthlyCalls=mutableListOf<MonthlyChargeCommandDto>();val statusCalls=mutableListOf<StatusCall>();var gate:CompletableDeferred<Unit>?=null;var statusResult:NetworkResult<VersionedChargeDto> = NetworkResult.Success(VersionedChargeDto(paidStatic(),"\"5\""));override suspend fun charges(groupId:String):NetworkResult<ChargeListDto>{chargeCalls++;return NetworkResult.Success(chargesStatic())};override suspend fun generateMonthly(groupId:String,command:MonthlyChargeCommandDto):NetworkResult<ChargeListDto>{monthlyCalls+=command;gate?.await();return NetworkResult.Success(ChargeListDto(listOf(chargeStatic("generated"))))};override suspend fun updateChargeStatus(groupId:String,chargeId:String,etag:String,command:ChargeStatusCommandDto):NetworkResult<VersionedChargeDto>{statusCalls+=StatusCall(chargeId,etag,command);return statusResult};override suspend fun expenses(groupId:String)=error("not used");override suspend fun createExpense(groupId:String,command:ExpenseWriteCommandDto)=error("not used");override suspend fun editExpense(groupId:String,expenseId:String,etag:String,command:ExpenseWriteCommandDto)=error("not used");override suspend fun voidExpense(groupId:String,expenseId:String,etag:String)=error("not used");override suspend fun totals(groupId:String)=error("not used")}
    private class FakeMemberships:RolesInvitesGateway{var calls=0;override suspend fun listMemberships(groupId:String):NetworkResult<List<MembershipDto>>{calls++;return NetworkResult.Success(listOf(MembershipDto(MEMBER,"Ana",GroupRoleDto.ATHLETE),MembershipDto(MEMBER2,"Bia",GroupRoleDto.ATHLETE)))};override suspend fun changeRole(groupId:String,userId:String,role:PersistedRoleDto)=error("not used");override suspend fun rotateInvite(groupId:String)=error("not used");override suspend fun expireInvite(groupId:String)=error("not used");override suspend fun redeem(code:String)=error("not used")}
    private class FakeStore(private val restored:MonthlyChargeDraft?):MonthlyChargeDraftStorePort{var reads=0;val writes=mutableListOf<MonthlyChargeDraft>();val clears=mutableListOf<Pair<String,String>>();var failWrites=false;override fun read(groupId:String,done:(MonthlyDraftReadResult)->Unit){reads++;done(MonthlyDraftReadResult.Success(restored))};override fun write(draft:MonthlyChargeDraft,done:(MonthlyDraftWriteResult)->Unit){writes+=draft;done(if(failWrites)MonthlyDraftWriteResult.Failure else MonthlyDraftWriteResult.Success)};override fun clear(groupId:String,commandKey:String,done:(MonthlyDraftWriteResult)->Unit){clears+=groupId to commandKey;done(MonthlyDraftWriteResult.Success)}}
    private companion object{const val GROUP="group";const val MEMBER="member-1";const val MEMBER2="member-2";const val CHARGE="charge-1";const val KEY="finance-key";fun chargeStatic(id:String=CHARGE)=ChargeDto(id,GROUP,MEMBER,ChargeKindDto.GAME,"game",null,2500,"2026-08-12",ChargeStatusDto.PENDING,false,4,emptyList());fun paidStatic()=chargeStatic().copy(status=ChargeStatusDto.PAID,version=5,events=listOf(ChargeEventDto("actor",ChargeStatusDto.PENDING,ChargeStatusDto.PAID,null,"2026-08-12T10:00:00Z")));fun chargesStatic()=ChargeListDto(listOf(chargeStatic(),chargeStatic("charge-2").copy(memberId=MEMBER2)),2500,5000,1000,7000)}
}
